name: Allure report to GitHub pages

on:
  push:
    branches:
      - main

jobs:
      
  build:
        
    runs-on: ubuntu-latest
  
    steps:
         
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install pipenv
              pipenv install --system
              playwright install chromium

      - name: run tests
        run: pytest

      - name: Allure Report action 
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: reports
          gh_pages: gh-pages
          allure_report: allure-report
       
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
